<?php
/**
 * Plugin Name:  Child Theme Plugin
 * Version:      1.0.0
 *
 * Description:  Provides modifications for the theme.
 * Plugin URI:   https://github.com/webmandesign/child-theme/
 * Author:       WebMan Design
 * Author URI:   https://www.webmandesign.eu/
 * License:      GPL-3.0-or-later
 * License URI:  https://www.gnu.org/licenses/gpl-3.0-standalone.html
 *
 * This theme, like WordPress, is licensed under the GPL.
 * Use it to make something cool, have fun, and share what you've learned with others.
 *
 * IMPORTANT:
 * Read the instructions in https://github.com/webmandesign/child-theme/blob/master/readme.md
 *
 * DO NOT EDIT THIS FILE!
 * Use `functions.php` file for your custom PHP functionality.
 * Use `style.css` file for your custom CSS styles.
 */

namespace WebManDesign\Child_Theme_Plugin;

use WP_Query;

// Exit if accessed directly.
defined( 'ABSPATH' ) || exit;

// Constants:
define( 'CHILD_THEME_PLUGIN_FILE', __FILE__ );
define( 'CHILD_THEME_PLUGIN_PATH', plugin_dir_path( CHILD_THEME_PLUGIN_FILE ) ); // Trailing slashed.
define( 'CHILD_THEME_PLUGIN_URL',  plugin_dir_url(  CHILD_THEME_PLUGIN_FILE ) ); // Trailing slashed.

// Plugin setup class.
class Setup {

	/**
	 * Stylesheet modification time cache.
	 *
	 * @access  public
	 * @var     string
	 */
	public static $stylesheet_filemtime = '';

	/**
	 * Initialization.
	 *
	 * @return  void
	 */
	public static function init() {

		// Processing

			self::$stylesheet_filemtime = filemtime( CHILD_THEME_PLUGIN_PATH . 'style.css' );

			add_action( 'init', __CLASS__ . '::editor_stylesheet', 1000 );

			add_action( 'wp_enqueue_scripts', __CLASS__ . '::enqueue_stylesheet', 1000 );

	} // /init

	/**
	 * Enqueue stylesheet file.
	 *
	 * @return  void
	 */
	public static function enqueue_stylesheet() {

		// Processing

			wp_enqueue_style(
				'child-theme-plugin-style',
				CHILD_THEME_PLUGIN_URL . 'style.css',
				array(),
				'v' . self::$stylesheet_filemtime
			);

	} // /enqueue_stylesheet

	/**
	 * Add editor stylesheet.
	 *
	 * @return  void
	 */
	public static function editor_stylesheet() {

		// Processing

			add_editor_style(
				esc_url_raw(
					add_query_arg(
						'ver',
						'v' . self::$stylesheet_filemtime,
						CHILD_THEME_PLUGIN_URL . 'style.css'
					)
				)
			);

	} // /editor_stylesheet

}

Setup::init();

// Load custom PHP functionality.
require_once CHILD_THEME_PLUGIN_PATH . 'functions.php';
